[package]
name = "cryptopals"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
hex = "0.4.3"
itertools = "0.14.0"
miette = "7.6.0"
phf = { version = "0.13.1", features = ["macros"] }
rand = "0.9.2"
thiserror = "2.0.17"
